 
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextJsTOpLoader from 'nextjs-toploader'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from "@/context/auth.context";
import GlobalContext from "@/context";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalContext>
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <ToastContainer/>
        <NextJsTOpLoader color="#fff" />
        {children}
        </body>
    </html>
    </GlobalContext>
  );
}
